# Generated by Django 5.0 on 2024-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_user_coins_remove_user_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('to_do', 'To Do'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
